# Generated by Django 3.2.5 on 2021-08-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='lastInteracted',
            field=models.IntegerField(default=-2),
        ),
    ]
