# Generated by Django 3.2.5 on 2021-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
