# Generated by Django 3.2.5 on 2021-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0004_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='theme',
            field=models.CharField(default='cardBlue', max_length=20),
        ),
    ]
