# Generated by Django 3.2.5 on 2021-08-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0005_auto_20210807_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
