# Generated by Django 3.2.5 on 2021-07-29 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0005_auto_20210728_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 15, 7, 11, 734355, tzinfo=utc))),
            ],
        ),
    ]
