# Generated by Django 3.2.5 on 2021-07-29 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0011_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 15, 28, 50, 402943, tzinfo=utc)),
        ),
    ]
