# Generated by Django 3.2.5 on 2021-07-29 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0017_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
