# Generated by Django 3.2.5 on 2021-07-29 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0018_alter_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='body',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='announcement',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='educationPortal.classroom'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
