# Generated by Django 3.2.5 on 2021-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0019_auto_20210729_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
