# Generated by Django 3.2.5 on 2021-07-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0022_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='userImages/blankUserIcon.svg', null=True, upload_to='userImages/'),
        ),
    ]
