# Generated by Django 3.2.5 on 2021-07-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0024_auto_20210730_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='texts',
            field=models.ManyToManyField(blank=True, to='educationPortal.Text'),
        ),
    ]
