# Generated by Django 3.2.5 on 2021-07-31 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0025_auto_20210730_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lastInteracted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
