# Generated by Django 3.2.5 on 2021-07-31 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0026_conversation_lastinteracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 31)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 31)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lastInteracted',
            field=models.DateField(default=datetime.date(2021, 7, 31)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 31)),
        ),
    ]
