# Generated by Django 3.2.5 on 2021-07-31 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0027_auto_20210730_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 30, 44, 792515)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 30, 44, 792515)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lastInteracted',
            field=models.DateField(default=datetime.datetime(2021, 7, 31, 15, 30, 44, 794545)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 30, 44, 793544)),
        ),
    ]
