# Generated by Django 3.2.5 on 2021-07-31 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0028_auto_20210731_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 51, 17, 614324)),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='lastInteracted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
