# Generated by Django 3.2.5 on 2021-08-01 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0036_auto_20210731_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 41, 7, 841382)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 41, 7, 837388)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 8, 41, 7, 841382)),
        ),
    ]
