# Generated by Django 3.2.5 on 2021-08-01 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0037_auto_20210801_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='givenFiles',
            field=models.ManyToManyField(blank=True, to='educationPortal.FileModel'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 12, 29, 55, 536441)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 12, 29, 55, 535444)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 12, 29, 55, 536441)),
        ),
    ]
