# Generated by Django 3.2.5 on 2021-08-01 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0038_auto_20210801_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 15, 1, 23, 988093)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 15, 1, 23, 988093)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 15, 1, 23, 988093)),
        ),
    ]
