# Generated by Django 3.2.5 on 2021-08-03 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0044_auto_20210802_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='returned',
            new_name='resubmitted',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 21, 53, 42, 530133)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 21, 53, 42, 530133)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 2, 21, 53, 42, 533125)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 21, 53, 42, 531129)),
        ),
    ]
