# Generated by Django 3.2.5 on 2021-08-04 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0046_auto_20210803_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 14, 39, 29, 269586)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 14, 39, 29, 268588)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='Untitled Quiz', max_length=1000),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 4, 14, 39, 29, 275289)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 4, 14, 39, 29, 274257)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 14, 39, 29, 269586)),
        ),
    ]
