# Generated by Django 3.2.5 on 2021-08-04 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0047_auto_20210804_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 15, 21, 27, 493313)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 15, 21, 27, 493313)),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='submissions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='submissions',
            field=models.ManyToManyField(blank=True, to='educationPortal.QuizSubmission'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 4, 15, 21, 27, 501303)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 4, 15, 21, 27, 497309)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 15, 21, 27, 493313)),
        ),
    ]
