# Generated by Django 3.2.5 on 2021-08-05 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0051_auto_20210805_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 15, 2, 20, 653522)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 15, 2, 20, 653522)),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 15, 2, 20, 661509)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 15, 2, 20, 657516)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 15, 2, 20, 653522)),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='answers',
            field=models.ManyToManyField(null=True, to='educationPortal.MCanswer'),
        ),
    ]
