# Generated by Django 3.2.5 on 2021-08-07 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationPortal', '0064_auto_20210807_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 19, 55, 41, 245177)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 19, 55, 41, 244212)),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 7, 19, 55, 41, 250196)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 7, 19, 55, 41, 247204)),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 19, 55, 41, 245177)),
        ),
    ]
